### ISSUE TITLE
qustion

### ISSUE THREAD

**Issue by zygmund2000** [UoC-Radio/JMPXRDS#7]
Hi,
I have question how to compile this code?

**Comment by gkiagia** [comment]
Run "autoreconf" to generate the "configure" script, then it's the usual configure, make, make install process...
```
autoreconf
./configure
make
make install
```

See also https://github.com/UoC-Radio/uoc-radio-overlay/blob/master/media-radio/jmpxrds/jmpxrds-9999.ebuild

@mickflemm can you add this in the README with the proper cmd line flags that I probably don't remember ?

**Comment by zygmund2000** [comment]
I tried like this but a lot of errors

`configure.ac:21: error: required file 'build-aux/compile' not found
configure.ac:21:   'automake --add-missing' can install 'compile'
configure.ac:5: error: required file 'build-aux/install-sh' not found
configure.ac:5:   'automake --add-missing' can install 'install-sh'
configure.ac:5: error: required file 'build-aux/missing' not found
configure.ac:5:   'automake --add-missing' can install 'missing'
Makefile.am: error: required file 'build-aux/depcomp' not found
Makefile.am:   'automake --add-missing' can install 'depcomp'
autoreconf: automake failed with exit status: 1`

I have Arch linux

**Comment by zygmund2000** [comment]
Ok I works now
Thaks

**Comment by mickflemm** [comment]
autoreconf -ivf
./configure
make
make install

Note that you also get jmpxrds_gui (unless you configure --without-gtk) but I still don't have an icon for it and you won't see it on your list of apps e.g. on GNOME.

**Comment by andimik** [comment]
and you need to install something first, this is for Ubuntu 22.04:

`sudo apt-get install libsoxr*`
